# Generated by Django 2.2.7 on 2019-11-18 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='телефон')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='отчество')),
                ('iin', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('\\d{12}', message='корректный ИИН должен состоять из 12 цифр')], verbose_name='ИИН')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('operator', models.CharField(blank=True, max_length=500, verbose_name='ФИО оператора КЦ')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Client', verbose_name='клиент')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.Region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'обращение в КЦ',
                'verbose_name_plural': 'обращения в КЦ',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(verbose_name='содержание жалобы')),
                ('status', models.CharField(blank=True, max_length=500, verbose_name='статус обращения')),
                ('actions', models.CharField(blank=True, max_length=500, verbose_name='принятые меры')),
                ('result', models.CharField(choices=[('explanations', 'даны разъяснения'), ('justified', 'жалоба обоснована'), ('not_justified', 'жалоба не обоснована')], default='explanations', max_length=100, verbose_name='результат')),
                ('client_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClientCall', verbose_name='обращение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization', verbose_name='МУ')),
            ],
            options={
                'verbose_name': 'жалоба',
                'verbose_name_plural': 'жалобы',
            },
        ),
    ]
