# Generated by Django 2.2.7 on 2019-11-18 11:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20191118_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='название')),
                ('text', models.TextField(blank=True, help_text='если нужно', verbose_name='пояснение')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
            },
        ),
        migrations.AddField(
            model_name='clientcall',
            name='topics',
            field=models.ManyToManyField(to='crm.Topic', verbose_name='темы'),
        ),
    ]
