# Generated by Django 2.2.7 on 2019-11-18 11:27

from django.db import migrations


def create_basic_topics(apps, schema_editor):
    Topic = apps.get_model('crm', 'Topic')
    topics_list = (
        "Некомпетентность", "Непредоставление КДУ", "Длительное ожидание КДУ",
        "Получение услуг на платной основе",
        "Отказ в госпитализации", "Отказ на постановку в ПБГ", "Качество оказания мед.помощи в стационаре",
        "Качество оказания мед.помощи в ПМСП", "Отказ в обслуживании вызова специалиста на дом",
        "Отсутствие специалистов", "Отказ в прикреплении", "Разъяснение по прикреплению",
        "Вопросы организационного характера", "Лекарственное обеспечение", "По пакетам ГОБМП и ОСМС",
        "Вопросы по отчислениям от юридических лиц", "Вопросы по взносам от физических лиц",
        "Вопросы по возвратам",
        "Вопросы не входящие в компетенцию Фонда",)
    for topic_str in topics_list:
        Topic.objects.create(name=topic_str)


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0005_auto_20191118_1722'),
    ]

    operations = [
        migrations.RunPython(create_basic_topics, reverse_code=migrations.RunPython.noop)
    ]
