# Generated by Django 2.2.7 on 2019-11-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20191122_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcall',
            name='topics',
        ),
        migrations.AddField(
            model_name='complaint',
            name='topics',
            field=models.ManyToManyField(blank=True, to='crm.Topic', verbose_name='темы'),
        ),
    ]
