# Generated by Django 2.2.7 on 2019-11-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20191122_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='text',
        ),
    ]
