# Generated by Django 2.2.7 on 2019-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_complaint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='text',
            field=models.TextField(verbose_name='текст обращения'),
        ),
    ]
