# Generated by Django 2.2.7 on 2019-11-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20191126_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='actions',
            field=models.TextField(blank=True, verbose_name='принятые меры'),
        ),
    ]
