# Generated by Django 2.2.7 on 2019-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20191129_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='result',
            field=models.CharField(blank=True, choices=[('explanations', 'даны разъяснения'), ('justified', 'жалоба обоснована'), ('not_justified', 'жалоба не обоснована')], default='explanations', max_length=100, verbose_name='результат'),
        ),
    ]
