# Generated by Django 2.2.7 on 2019-12-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20191129_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='complaint',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Complaint', verbose_name='жалоба'),
        ),
        migrations.AlterField(
            model_name='clientcall',
            name='consultation',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Consultation', verbose_name='консультация'),
        ),
    ]
