# Generated by Django 2.2.7 on 2019-11-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcall',
            name='kind',
            field=models.CharField(choices=[('consultation', 'консультация'), ('complaint', 'жалоба'), ('thanks', 'благодарность')], default='consultation', max_length=100, verbose_name='вид'),
        ),
    ]
