# Generated by Django 2.2.7 on 2019-11-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20191119_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='client_call',
        ),
        migrations.AddField(
            model_name='clientcall',
            name='complaint',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Complaint', verbose_name='жалоба'),
        ),
    ]
