# Generated by Django 2.2.7 on 2019-11-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('crm', '0010_auto_20191120_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='organization',
        ),
        migrations.AddField(
            model_name='clientcall',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization', verbose_name='МУ'),
        ),
    ]
