# Generated by Django 2.2.7 on 2019-11-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20191122_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcall',
            old_name='comment',
            new_name='text',
        ),
    ]
