# Generated by Django 2.2.7 on 2019-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20191122_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcall',
            name='answer',
            field=models.TextField(blank=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='clientcall',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст обращения'),
        ),
    ]
