# Generated by Django 2.2.7 on 2019-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20191129_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='kind',
            field=models.CharField(choices=[('consultation', 'консультация'), ('complaint', 'жалоба'), ('thanks', 'благодарность'), ('wrong_call', 'ошибочный звонок'), ('interrupted_call', 'прерывание связи'), ('proposal', 'предложение')], default='consultation', max_length=100, verbose_name='вид'),
        ),
    ]
