# Generated by Django 2.2.7 on 2019-11-28 11:20

from django.db import migrations


def create_first_survey(apps, schema_editor):
    Survey = apps.get_model('surveys', 'Survey')
    Question = apps.get_model('surveys', 'Question')
    Choice = apps.get_model('surveys', 'Choice')

    survey = Survey.objects.create(name='Опрос по входящим звонкам в КЦ')
    question_1 = Question.objects.create(survey=survey,
                                         text='Как часто Вы обращаетесь за медицинской помощью?')
    Choice.objects.create(question=question_1, text='Часто')
    Choice.objects.create(question=question_1, text='Редко')
    Choice.objects.create(question=question_1, text='Никогда')
    question_2 = Question.objects.create(survey=survey,
                                         text='Удовлетворены ли Вы качеством оказанием медицинской помощи?')
    Choice.objects.create(question=question_2, text='Да')
    Choice.objects.create(question=question_2, text='Нет')
    question_3 = Question.objects.create(survey=survey,
                                         text='Знаете ли Вы о внедрении ОСМС в Казахстане?')
    Choice.objects.create(question=question_3, text='Да')
    Choice.objects.create(question=question_3, text='Нет')



class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_first_survey, reverse_code=migrations.RunPython.noop)
    ]
