# Generated by Django 2.2.7 on 2019-12-04 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_create_first_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='client',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Client', verbose_name='гражданин'),
        ),
    ]
