# Generated by Django 4.0.3 on 2022-04-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_new', '0002_remove_sratio_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sregion',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='sregion',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='sregion',
            name='code_op',
        ),
        migrations.RemoveField(
            model_name='sregion',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='sregion',
            name='st_city',
        ),
        migrations.RemoveField(
            model_name='sregion',
            name='st_view',
        ),
        migrations.RemoveField(
            model_name='sregion',
            name='status',
        ),
    ]
