# Generated by Django 4.0.3 on 2022-04-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_new', '0003_remove_sregion_checkbox_remove_sregion_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svillage',
            name='township_id',
        ),
        migrations.RemoveField(
            model_name='svillage',
            name='village_id',
        ),
    ]
