# Generated by Django 4.0.3 on 2022-04-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_new', '0004_remove_svillage_township_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sstreet',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='sstreet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sstreet',
            name='streettype_id',
        ),
    ]
