# Generated by Django 4.0.3 on 2022-04-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_new', '0005_remove_sstreet_city_id_remove_sstreet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sstreet',
            name='city_id',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
        migrations.AddField(
            model_name='sstreet',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
        migrations.AddField(
            model_name='sstreet',
            name='streettype_id',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
    ]
