# Generated by Django 4.0.3 on 2022-04-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_new', '0006_sstreet_city_id_sstreet_status_sstreet_streettype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sstreet',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='sstreet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sstreet',
            name='streettype_id',
        ),
    ]
